### ISSUE TITLE
您好，有hex或者bin转换dfu的类吗？

### ISSUE THREAD

**Issue by Dreamskya** [NguyenTrongThinh/STM32Flasher#2]
您好，作者，dfu转换，有工具类吗？对hex或者bin文件转换成dfu

**Comment by NguyenTrongThinh** [comment]
此应用程序中没有任何类可将bin转换为dfu。我使用此工具将bin转换为dfu“ DfuSe”. 

https://drive.google.com/file/d/18_h8v8c9qe7aYlaiXoTHsvbQ_SnZkwkt/view?usp=drivesdk

**Comment by Dreamskya** [comment]
@NguyenTrongThinh java 把Hex转dfu有这个的吗？要借用额外工具来转dfu，这样会有些繁琐了。
